### ISSUE TITLE
Getting Error while uploading the email path

### ISSUE THREAD

**Issue by Arinze1020** [lazyprogrammerrr/LazyMails-CLI_Version#1]
Choose Your Email List File Here 
You Can Also Paste The Path Link Of File 'Using Shift + Right Click'-> /home/arinze/Desktop/bettingAbs/LazyMails-CLI_Version/emails.csv
File Not Found!

I don't know what am doing wrong.

**Comment by lazyprogrammerrr** [comment]
-Make a xlsx file.
-Like emails.xlsx
-And thanks for rasing issue i will update the code for error handling.

**Comment by lazyprogrammerrr** [comment]
Or you can just create a email.xlsx file from where you running this script.

**Comment by Arinze1020** [comment]
Yes the emails.xlsx is inside the same folder as these scripts, I tried to change it to CSV  but I was still getting the same erorr

**Comment by Arinze1020** [comment]
could you give an example of how  I could call the file, I even make use of the relative path but was still getting the file, not in the path

**Comment by lazyprogrammerrr** [comment]
**my script currently not handling csv files right now.** sorry for that you have to use xlsx file and it will work for sure

**Comment by lazyprogrammerrr** [comment]
Updated Code for csv file also. Please run the script again and if you find some other issue raise here. Thankyou for letting me know about this issue!

**Comment by Arinze1020** [comment]
Working Great Job
